/** @type {import('../types.d.ts').AlphaRecipe[]} */
export const braiseRecipes = [
  {
    slug: 'ga-rang-gung', title: 'Gà rang gừng', version: 1, servings: 4,
    prepTimeMinutes: 15, cookTimeMinutes: 30,
    summary: 'Thịt gà chín kỹ, thơm gừng và có lớp sốt mặn ngọt vừa phải.',
    ingredients: [
      { slug: 'thit-ga', name: 'Thịt gà', category: 'protein', quantity: 700, unit: 'g', preparation: 'chặt miếng vừa ăn', note: 'Có thể dùng đùi gà', scalingMode: 'LINEAR', scalingExponent: 1, roundingIncrement: 25 },
      { slug: 'gung', name: 'Gừng', category: 'aromatic', quantity: 30, unit: 'g', preparation: 'thái sợi', note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.8, roundingIncrement: 2, adjustments: [{ dimensionKey: 'spiciness', sensitivity: 0.2, minFactor: 0.8, maxFactor: 1.2 }] },
      { slug: 'hanh-kho', name: 'Hành tím', category: 'aromatic', quantity: 3, unit: 'củ', preparation: 'băm nhỏ', note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.8, roundingIncrement: 0.5 },
      { slug: 'nuoc-mam', name: 'Nước mắm', category: 'seasoning', quantity: 25, unit: 'ml', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.75, roundingIncrement: 1, adjustments: [{ dimensionKey: 'saltiness', sensitivity: 0.3, minFactor: 0.75, maxFactor: 1.2 }] },
      { slug: 'duong', name: 'Đường', category: 'seasoning', quantity: 1, unit: 'muỗng canh', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.75, roundingIncrement: 0.25, adjustments: [{ dimensionKey: 'sweetness', sensitivity: 0.3, minFactor: 0.75, maxFactor: 1.25 }] },
      { slug: 'dau-an', name: 'Dầu ăn', category: 'fat', quantity: 15, unit: 'ml', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.7, roundingIncrement: 1 },
      { slug: 'tieu-den', name: 'Tiêu đen', category: 'seasoning', quantity: 1, unit: 'g', preparation: 'xay', note: null, scalingMode: 'FIXED', scalingExponent: 1, roundingIncrement: 0.1 },
    ],
    steps: [
      { stepNo: 1, instruction: 'Ướp gà với nước mắm, một nửa gừng, hành tím và đường.', durationSeconds: 600, heatLevel: null, tip: 'Giữ thịt trong ngăn mát trong lúc ướp.' },
      { stepNo: 2, instruction: 'Làm nóng dầu, cho phần gừng còn lại vào đảo đến khi thơm.', durationSeconds: 60, heatLevel: 'vừa', tip: null },
      { stepNo: 3, instruction: 'Cho gà vào đảo đều đến khi bề mặt săn lại.', durationSeconds: 420, heatLevel: 'vừa-lớn', tip: null },
      { stepNo: 4, instruction: 'Thêm một ít nước, đậy hé nắp và nấu đến khi thịt gà chín kỹ, nước sốt còn sệt.', durationSeconds: 900, heatLevel: 'nhỏ', tip: 'Phần dày nhất của thịt phải chín hoàn toàn, không còn màu hồng.' },
      { stepNo: 5, instruction: 'Mở nắp, đảo cho sốt bám quanh thịt, rắc tiêu rồi tắt bếp.', durationSeconds: 120, heatLevel: 'vừa', tip: null },
    ],
  },
  {
    slug: 'thit-kho-trung', title: 'Thịt kho trứng', version: 1, servings: 4,
    prepTimeMinutes: 20, cookTimeMinutes: 55,
    summary: 'Thịt heo mềm và trứng thấm nước kho trong, vị mặn ngọt dịu.',
    ingredients: [
      { slug: 'thit-ba-chi', name: 'Thịt ba chỉ', category: 'protein', quantity: 600, unit: 'g', preparation: 'cắt miếng vuông', note: null, scalingMode: 'LINEAR', scalingExponent: 1, roundingIncrement: 25 },
      { slug: 'trung-ga', name: 'Trứng gà', category: 'protein', quantity: 4, unit: 'quả', preparation: 'luộc chín, bóc vỏ', note: null, scalingMode: 'LINEAR', scalingExponent: 1, roundingIncrement: 1 },
      { slug: 'nuoc-dua', name: 'Nước dừa', category: 'liquid', quantity: 500, unit: 'ml', preparation: null, note: 'Có thể thay bằng nước', scalingMode: 'LINEAR', scalingExponent: 1, roundingIncrement: 25 },
      { slug: 'nuoc-mam', name: 'Nước mắm', category: 'seasoning', quantity: 35, unit: 'ml', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.75, roundingIncrement: 2, adjustments: [{ dimensionKey: 'saltiness', sensitivity: 0.35, minFactor: 0.7, maxFactor: 1.2 }] },
      { slug: 'duong', name: 'Đường', category: 'seasoning', quantity: 2, unit: 'muỗng canh', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.75, roundingIncrement: 0.25, adjustments: [{ dimensionKey: 'sweetness', sensitivity: 0.35, minFactor: 0.7, maxFactor: 1.25 }] },
      { slug: 'hanh-kho', name: 'Hành tím', category: 'aromatic', quantity: 3, unit: 'củ', preparation: 'băm nhỏ', note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.8, roundingIncrement: 0.5 },
      { slug: 'tieu-den', name: 'Tiêu đen', category: 'seasoning', quantity: 1, unit: 'g', preparation: 'xay', note: null, scalingMode: 'FIXED', scalingExponent: 1, roundingIncrement: 0.1 },
    ],
    steps: [
      { stepNo: 1, instruction: 'Ướp thịt với hành, một nửa nước mắm và một nửa đường.', durationSeconds: 900, heatLevel: null, tip: 'Giữ thịt mát trong lúc ướp.' },
      { stepNo: 2, instruction: 'Cho phần đường còn lại vào nồi với chút nước, đun đến màu hổ phách nhạt.', durationSeconds: 180, heatLevel: 'nhỏ', tip: 'Không để đường chuyển đen vì sẽ đắng.' },
      { stepNo: 3, instruction: 'Cho thịt vào đảo đến khi săn, sau đó thêm nước dừa và phần nước mắm còn lại.', durationSeconds: 420, heatLevel: 'vừa', tip: null },
      { stepNo: 4, instruction: 'Hớt bọt, hạ lửa và kho đến khi thịt mềm, chín kỹ.', durationSeconds: 1800, heatLevel: 'nhỏ', tip: 'Châm thêm nước nóng nếu nước kho cạn quá nhanh.' },
      { stepNo: 5, instruction: 'Cho trứng đã luộc vào, kho thêm để trứng thấm vị rồi rắc tiêu.', durationSeconds: 600, heatLevel: 'nhỏ', tip: null },
    ],
  },
  {
    slug: 'ca-kho-tieu', title: 'Cá kho tiêu', version: 1, servings: 3,
    prepTimeMinutes: 15, cookTimeMinutes: 30,
    summary: 'Cá kho chín kỹ trong sốt tiêu mặn ngọt, hợp dùng cùng cơm nóng.',
    ingredients: [
      { slug: 'ca-cat-khuc', name: 'Cá cắt khúc', category: 'protein', quantity: 500, unit: 'g', preparation: 'rửa sạch, thấm khô', note: 'Chọn loại cá phù hợp để kho', scalingMode: 'LINEAR', scalingExponent: 1, roundingIncrement: 25 },
      { slug: 'nuoc-mam', name: 'Nước mắm', category: 'seasoning', quantity: 25, unit: 'ml', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.75, roundingIncrement: 1, adjustments: [{ dimensionKey: 'saltiness', sensitivity: 0.35, minFactor: 0.7, maxFactor: 1.2 }] },
      { slug: 'duong', name: 'Đường', category: 'seasoning', quantity: 1, unit: 'muỗng canh', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.75, roundingIncrement: 0.25, adjustments: [{ dimensionKey: 'sweetness', sensitivity: 0.3, minFactor: 0.75, maxFactor: 1.25 }] },
      { slug: 'hanh-kho', name: 'Hành tím', category: 'aromatic', quantity: 2, unit: 'củ', preparation: 'thái mỏng', note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.8, roundingIncrement: 0.5 },
      { slug: 'tieu-den', name: 'Tiêu đen', category: 'seasoning', quantity: 2, unit: 'g', preparation: 'xay thô', note: null, scalingMode: 'FIXED', scalingExponent: 1, roundingIncrement: 0.1, adjustments: [{ dimensionKey: 'spiciness', sensitivity: 0.35, minFactor: 0.7, maxFactor: 1.3 }] },
      { slug: 'dau-an', name: 'Dầu ăn', category: 'fat', quantity: 10, unit: 'ml', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.7, roundingIncrement: 1 },
    ],
    steps: [
      { stepNo: 1, instruction: 'Ướp cá với nước mắm, hành tím, một nửa tiêu và đường.', durationSeconds: 600, heatLevel: null, tip: 'Giữ cá mát trong lúc ướp.' },
      { stepNo: 2, instruction: 'Làm nóng dầu trong nồi, xếp cá vào và áp nhẹ hai mặt.', durationSeconds: 240, heatLevel: 'vừa', tip: 'Lật nhẹ tay để cá không vỡ.' },
      { stepNo: 3, instruction: 'Thêm nước vừa xâm xấp, đun sôi rồi hạ lửa.', durationSeconds: 180, heatLevel: 'vừa', tip: null },
      { stepNo: 4, instruction: 'Kho liu riu đến khi cá chín kỹ và nước kho sánh lại.', durationSeconds: 900, heatLevel: 'nhỏ', tip: 'Thịt cá phải đục và dễ tách, không còn phần trong sống.' },
      { stepNo: 5, instruction: 'Rắc phần tiêu còn lại, nếm nước kho rồi tắt bếp.', durationSeconds: 60, heatLevel: 'nhỏ', tip: null },
    ],
  },
  {
    slug: 'ga-kho-sa', title: 'Gà kho sả', version: 1, servings: 4,
    prepTimeMinutes: 15, cookTimeMinutes: 32,
    summary: 'Gà kho sả thơm, chín mềm với chút cay ấm và phần sốt đậm vừa.',
    ingredients: [
      { slug: 'thit-ga', name: 'Thịt gà', category: 'protein', quantity: 700, unit: 'g', preparation: 'chặt miếng vừa ăn', note: null, scalingMode: 'LINEAR', scalingExponent: 1, roundingIncrement: 25 },
      { slug: 'sa', name: 'Sả', category: 'aromatic', quantity: 4, unit: 'nhánh', preparation: 'băm nhỏ phần non', note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.8, roundingIncrement: 0.5 },
      { slug: 'toi', name: 'Tỏi', category: 'aromatic', quantity: 3, unit: 'tép', preparation: 'băm nhỏ', note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.8, roundingIncrement: 1 },
      { slug: 'nuoc-mam', name: 'Nước mắm', category: 'seasoning', quantity: 25, unit: 'ml', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.75, roundingIncrement: 1, adjustments: [{ dimensionKey: 'saltiness', sensitivity: 0.3, minFactor: 0.75, maxFactor: 1.2 }] },
      { slug: 'duong', name: 'Đường', category: 'seasoning', quantity: 1, unit: 'muỗng canh', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.75, roundingIncrement: 0.25, adjustments: [{ dimensionKey: 'sweetness', sensitivity: 0.25, minFactor: 0.75, maxFactor: 1.25 }] },
      { slug: 'ot', name: 'Ớt', category: 'aromatic', quantity: 1, unit: 'trái', preparation: 'thái lát', note: 'Có thể giảm hoặc bỏ', scalingMode: 'FIXED', scalingExponent: 1, roundingIncrement: 0.5, adjustments: [{ dimensionKey: 'spiciness', sensitivity: 0.5, minFactor: 0.5, maxFactor: 1.5 }] },
      { slug: 'dau-an', name: 'Dầu ăn', category: 'fat', quantity: 15, unit: 'ml', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.7, roundingIncrement: 1 },
    ],
    steps: [
      { stepNo: 1, instruction: 'Ướp gà với một nửa sả, tỏi, nước mắm và đường.', durationSeconds: 600, heatLevel: null, tip: 'Giữ gà mát trong lúc ướp.' },
      { stepNo: 2, instruction: 'Làm nóng dầu, đảo phần sả còn lại và ớt đến khi thơm.', durationSeconds: 90, heatLevel: 'vừa', tip: null },
      { stepNo: 3, instruction: 'Cho gà vào đảo đến khi các mặt săn lại.', durationSeconds: 420, heatLevel: 'vừa-lớn', tip: null },
      { stepNo: 4, instruction: 'Thêm ít nước, đậy hé nắp và kho đến khi thịt gà chín kỹ.', durationSeconds: 900, heatLevel: 'nhỏ', tip: 'Phần thịt sát xương phải chín hoàn toàn, không còn màu hồng.' },
      { stepNo: 5, instruction: 'Mở nắp, đảo đến khi nước kho sánh và bám quanh thịt.', durationSeconds: 180, heatLevel: 'vừa', tip: null },
    ],
  },
];
