/** @type {import('../types.d.ts').AlphaRecipe[]} */
export const everydayRecipes = [
  {
    slug: 'trung-chien-thit-bam',
    title: 'Trứng chiên thịt băm',
    version: 2,
    servings: 2,
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    summary: 'Trứng mềm, thịt băm chín tới và vị mặn dịu cho bữa cơm nhanh.',
    ingredients: [
      { slug: 'trung-ga', name: 'Trứng gà', category: 'protein', quantity: 3, unit: 'quả', preparation: null, note: null, scalingMode: 'LINEAR', scalingExponent: 1, roundingIncrement: 0.5 },
      { slug: 'thit-heo-bam', name: 'Thịt heo băm', category: 'protein', quantity: 100, unit: 'g', preparation: null, note: null, scalingMode: 'LINEAR', scalingExponent: 1, roundingIncrement: 5 },
      { slug: 'nuoc-mam', name: 'Nước mắm', category: 'seasoning', quantity: 8, unit: 'ml', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.75, roundingIncrement: 1, adjustments: [{ dimensionKey: 'saltiness', sensitivity: 0.3, minFactor: 0.7, maxFactor: 1.2 }] },
      { slug: 'hanh-la', name: 'Hành lá', category: 'vegetable', quantity: 15, unit: 'g', preparation: 'thái nhỏ', note: null, scalingMode: 'LINEAR', scalingExponent: 1, roundingIncrement: 1, adjustments: [{ dimensionKey: 'garlic_onion', sensitivity: 0.4, minFactor: 0.8, maxFactor: 1.3 }] },
      { slug: 'dau-an', name: 'Dầu ăn', category: 'fat', quantity: 10, unit: 'ml', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.7, roundingIncrement: 1 },
      { slug: 'tieu-den', name: 'Tiêu đen', category: 'seasoning', quantity: 0.5, unit: 'g', preparation: 'xay', note: null, scalingMode: 'FIXED', scalingExponent: 1, roundingIncrement: 0.1 },
    ],
    steps: [
      { stepNo: 1, instruction: 'Đập trứng vào tô, cho thịt băm, nước mắm, hành lá và tiêu rồi trộn đều.', durationSeconds: 120, heatLevel: null, tip: 'Trộn vừa đều, không cần đánh quá mạnh.' },
      { stepNo: 2, instruction: 'Làm nóng chảo ở lửa vừa, cho dầu ăn vào và láng đều mặt chảo.', durationSeconds: 60, heatLevel: 'vừa', tip: null },
      { stepNo: 3, instruction: 'Đổ hỗn hợp vào chảo, dàn đều và chiên đến khi mặt dưới se vàng.', durationSeconds: 180, heatLevel: 'vừa-nhỏ', tip: 'Giảm lửa nếu mặt dưới vàng quá nhanh.' },
      { stepNo: 4, instruction: 'Lật hoặc chia miếng, nấu đến khi phần thịt bên trong chín hẳn và không còn màu hồng.', durationSeconds: 120, heatLevel: 'vừa-nhỏ', tip: 'Quan sát độ chín của thịt thay vì chỉ dựa vào thời gian.' },
    ],
  },
  {
    slug: 'dau-phu-sot-ca-chua',
    title: 'Đậu phụ sốt cà chua',
    version: 1,
    servings: 3,
    prepTimeMinutes: 10,
    cookTimeMinutes: 18,
    summary: 'Đậu phụ áp chảo thấm sốt cà chua chua ngọt nhẹ, dễ ăn cùng cơm.',
    ingredients: [
      { slug: 'dau-phu', name: 'Đậu phụ', category: 'protein', quantity: 4, unit: 'miếng', preparation: 'thấm khô, cắt miếng', note: null, scalingMode: 'LINEAR', scalingExponent: 1, roundingIncrement: 0.5 },
      { slug: 'ca-chua', name: 'Cà chua', category: 'vegetable', quantity: 3, unit: 'quả', preparation: 'bổ múi cau', note: null, scalingMode: 'LINEAR', scalingExponent: 1, roundingIncrement: 0.5 },
      { slug: 'hanh-kho', name: 'Hành tím', category: 'aromatic', quantity: 2, unit: 'củ', preparation: 'băm nhỏ', note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.8, roundingIncrement: 0.5 },
      { slug: 'nuoc-mam', name: 'Nước mắm', category: 'seasoning', quantity: 12, unit: 'ml', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.75, roundingIncrement: 1, adjustments: [{ dimensionKey: 'saltiness', sensitivity: 0.25, minFactor: 0.75, maxFactor: 1.2 }] },
      { slug: 'duong', name: 'Đường', category: 'seasoning', quantity: 1, unit: 'muỗng cà phê', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.75, roundingIncrement: 0.25, adjustments: [{ dimensionKey: 'sweetness', sensitivity: 0.25, minFactor: 0.75, maxFactor: 1.25 }] },
      { slug: 'dau-an', name: 'Dầu ăn', category: 'fat', quantity: 20, unit: 'ml', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.7, roundingIncrement: 2 },
      { slug: 'hanh-la', name: 'Hành lá', category: 'vegetable', quantity: 10, unit: 'g', preparation: 'thái nhỏ', note: null, scalingMode: 'LINEAR', scalingExponent: 1, roundingIncrement: 1 },
    ],
    steps: [
      { stepNo: 1, instruction: 'Áp chảo đậu phụ với một nửa lượng dầu đến khi các mặt vàng nhẹ rồi gắp ra.', durationSeconds: 420, heatLevel: 'vừa', tip: 'Thấm khô đậu để hạn chế bắn dầu.' },
      { stepNo: 2, instruction: 'Phi hành tím với phần dầu còn lại, thêm cà chua và một nhúm nước, đảo đến khi mềm.', durationSeconds: 300, heatLevel: 'vừa', tip: null },
      { stepNo: 3, instruction: 'Nêm nước mắm và đường, cho đậu vào đảo nhẹ để phủ sốt.', durationSeconds: 180, heatLevel: 'nhỏ', tip: 'Không đảo mạnh để đậu không vỡ.' },
      { stepNo: 4, instruction: 'Đun nhỏ lửa đến khi sốt sánh vừa, rắc hành lá rồi tắt bếp.', durationSeconds: 180, heatLevel: 'nhỏ', tip: null },
    ],
  },
  {
    slug: 'trung-sot-ca-chua',
    title: 'Trứng sốt cà chua',
    version: 1,
    servings: 2,
    prepTimeMinutes: 8,
    cookTimeMinutes: 12,
    summary: 'Trứng mềm quyện cà chua mọng, hợp cho bữa sáng hoặc bữa cơm nhanh.',
    ingredients: [
      { slug: 'trung-ga', name: 'Trứng gà', category: 'protein', quantity: 3, unit: 'quả', preparation: 'đánh tan', note: null, scalingMode: 'LINEAR', scalingExponent: 1, roundingIncrement: 0.5 },
      { slug: 'ca-chua', name: 'Cà chua', category: 'vegetable', quantity: 2, unit: 'quả', preparation: 'cắt múi nhỏ', note: null, scalingMode: 'LINEAR', scalingExponent: 1, roundingIncrement: 0.5 },
      { slug: 'hanh-la', name: 'Hành lá', category: 'vegetable', quantity: 10, unit: 'g', preparation: 'thái nhỏ', note: null, scalingMode: 'LINEAR', scalingExponent: 1, roundingIncrement: 1 },
      { slug: 'nuoc-mam', name: 'Nước mắm', category: 'seasoning', quantity: 6, unit: 'ml', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.75, roundingIncrement: 1, adjustments: [{ dimensionKey: 'saltiness', sensitivity: 0.25, minFactor: 0.75, maxFactor: 1.2 }] },
      { slug: 'duong', name: 'Đường', category: 'seasoning', quantity: 0.5, unit: 'muỗng cà phê', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.75, roundingIncrement: 0.25 },
      { slug: 'dau-an', name: 'Dầu ăn', category: 'fat', quantity: 12, unit: 'ml', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.7, roundingIncrement: 1 },
    ],
    steps: [
      { stepNo: 1, instruction: 'Làm nóng một nửa dầu, cho trứng vào đảo thành miếng mềm vừa chín rồi lấy ra.', durationSeconds: 120, heatLevel: 'vừa', tip: 'Không đảo quá lâu để trứng còn mềm.' },
      { stepNo: 2, instruction: 'Thêm dầu còn lại và cà chua, đảo đến khi cà chua mềm ra nước.', durationSeconds: 240, heatLevel: 'vừa', tip: null },
      { stepNo: 3, instruction: 'Nêm nước mắm, đường và một ít nước; cho trứng trở lại chảo.', durationSeconds: 120, heatLevel: 'nhỏ', tip: null },
      { stepNo: 4, instruction: 'Đảo nhẹ cho trứng thấm sốt, rắc hành lá rồi tắt bếp.', durationSeconds: 60, heatLevel: 'nhỏ', tip: null },
    ],
  },
  {
    slug: 'thit-bam-sot-ca-chua',
    title: 'Thịt băm sốt cà chua',
    version: 1,
    servings: 3,
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    summary: 'Thịt băm tơi, chín kỹ trong sốt cà chua đậm vừa và dễ dùng với cơm.',
    ingredients: [
      { slug: 'thit-heo-bam', name: 'Thịt heo băm', category: 'protein', quantity: 250, unit: 'g', preparation: null, note: null, scalingMode: 'LINEAR', scalingExponent: 1, roundingIncrement: 10 },
      { slug: 'ca-chua', name: 'Cà chua', category: 'vegetable', quantity: 3, unit: 'quả', preparation: 'cắt hạt lựu', note: null, scalingMode: 'LINEAR', scalingExponent: 1, roundingIncrement: 0.5 },
      { slug: 'hanh-kho', name: 'Hành tím', category: 'aromatic', quantity: 2, unit: 'củ', preparation: 'băm nhỏ', note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.8, roundingIncrement: 0.5 },
      { slug: 'nuoc-mam', name: 'Nước mắm', category: 'seasoning', quantity: 12, unit: 'ml', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.75, roundingIncrement: 1, adjustments: [{ dimensionKey: 'saltiness', sensitivity: 0.3, minFactor: 0.75, maxFactor: 1.2 }] },
      { slug: 'dau-an', name: 'Dầu ăn', category: 'fat', quantity: 10, unit: 'ml', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.7, roundingIncrement: 1 },
      { slug: 'tieu-den', name: 'Tiêu đen', category: 'seasoning', quantity: 0.5, unit: 'g', preparation: 'xay', note: null, scalingMode: 'FIXED', scalingExponent: 1, roundingIncrement: 0.1 },
    ],
    steps: [
      { stepNo: 1, instruction: 'Phi hành tím thơm với dầu ăn rồi cho thịt băm vào đảo tơi.', durationSeconds: 240, heatLevel: 'vừa', tip: 'Tách các cụm thịt để thịt chín đều.' },
      { stepNo: 2, instruction: 'Tiếp tục đảo đến khi thịt đổi màu hoàn toàn và không còn phần hồng.', durationSeconds: 180, heatLevel: 'vừa', tip: 'Quan sát độ chín thay vì chỉ dựa vào thời gian.' },
      { stepNo: 3, instruction: 'Cho cà chua vào, nêm nước mắm và đảo đến khi cà chua mềm.', durationSeconds: 300, heatLevel: 'vừa-nhỏ', tip: null },
      { stepNo: 4, instruction: 'Đun đến khi sốt sánh vừa, rắc tiêu và nếm lại trước khi tắt bếp.', durationSeconds: 120, heatLevel: 'nhỏ', tip: null },
    ],
  },
  {
    slug: 'cai-thia-xao-toi',
    title: 'Cải thìa xào tỏi',
    version: 1,
    servings: 3,
    prepTimeMinutes: 10,
    cookTimeMinutes: 8,
    summary: 'Cải thìa xanh giòn, thơm tỏi với phần sốt mỏng vừa đủ.',
    ingredients: [
      { slug: 'cai-thia', name: 'Cải thìa', category: 'vegetable', quantity: 500, unit: 'g', preparation: 'tách bẹ, rửa sạch', note: null, scalingMode: 'LINEAR', scalingExponent: 1, roundingIncrement: 25 },
      { slug: 'toi', name: 'Tỏi', category: 'aromatic', quantity: 4, unit: 'tép', preparation: 'băm nhỏ', note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.8, roundingIncrement: 1, adjustments: [{ dimensionKey: 'garlic_onion', sensitivity: 0.35, minFactor: 0.75, maxFactor: 1.3 }] },
      { slug: 'dau-an', name: 'Dầu ăn', category: 'fat', quantity: 15, unit: 'ml', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.7, roundingIncrement: 1 },
      { slug: 'nuoc-mam', name: 'Nước mắm', category: 'seasoning', quantity: 8, unit: 'ml', preparation: null, note: null, scalingMode: 'CONSERVATIVE', scalingExponent: 0.75, roundingIncrement: 1, adjustments: [{ dimensionKey: 'saltiness', sensitivity: 0.25, minFactor: 0.75, maxFactor: 1.2 }] },
      { slug: 'duong', name: 'Đường', category: 'seasoning', quantity: 0.25, unit: 'muỗng cà phê', preparation: null, note: null, scalingMode: 'FIXED', scalingExponent: 1, roundingIncrement: 0.25 },
    ],
    steps: [
      { stepNo: 1, instruction: 'Để cải thật ráo; pha nước mắm và đường với một ít nước.', durationSeconds: 120, heatLevel: null, tip: 'Rau ráo nước sẽ xào nhanh và ít bắn dầu.' },
      { stepNo: 2, instruction: 'Làm nóng chảo, cho dầu và tỏi vào đảo nhanh đến khi thơm.', durationSeconds: 30, heatLevel: 'vừa-lớn', tip: 'Không để tỏi chuyển nâu sẫm.' },
      { stepNo: 3, instruction: 'Cho phần bẹ cải vào trước, đảo nhanh rồi thêm phần lá.', durationSeconds: 150, heatLevel: 'lớn', tip: null },
      { stepNo: 4, instruction: 'Rưới hỗn hợp gia vị, đảo đến khi cải vừa chín và còn xanh rồi tắt bếp.', durationSeconds: 90, heatLevel: 'lớn', tip: 'Không xào quá lâu để rau giữ độ giòn.' },
    ],
  },
];
